### PR TITLE
Adds .travis.yml

### PR DESCRIPTION
**Pull request by petems**

### CODE REVIEW

**Comment by creature** [comment]
Thanks for this! I'm not familiar with Travis-CI – what's the effect of adding this file? Should it be `rails server` and not, say, `rake test`?

**Comment by petems** [comment]
Yep, it should be the rake test, let me fix that

TravisCI is this: https://travis-ci.org/ 

It's the bees knees for all open-source projects, completely free continuous testing on your app. Automatic CI on all branches and pull-requests, with all the alerting you'd need for errors coming up and such.

**Comment by creature** [comment]
Great, thanks! I've merged the PR; let me know if there's something else I should do to get the full benefit from it.

**Comment by petems** [comment]
Ok, easiest way to benefit:

Log into Travis-CI.org
Sync your repos
Tick the box on this repo to enable continuous integration
Then after that, every git checkin you make will have a CI run where it runs your tests!

If you want a hand, ping me on Gitter: https://gitter.im/petems/localwelcome

Hope it's useful! :+1:

**Pull request merged**
